openapi: 3.0.0
info:
  title: startrek api
  description: |
   A list of star trek episodes by seasone
  termsOfService: http://startrek/terms
  contact:
    email: abderahmane.toumi.etd@univ-tiaret.dz
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
- url: http://localhost:8080/startrek/api/1.0.0
tags:
- name: episode
  description: Everything about episodes
- name: seasone
  description: Everything about seasones
paths:
  /seasons/episodes:
    get:
      tags:
      - episode
      summary: Get all episodes by seasons
      description: Returns all episodes by seasons 
      operationId: getEpisodesBySeasons
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/seasons'
        # Definition of all error statuses
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-swagger-router-controller: Seasone
components:
  schemas:
    seasons:
      type: object
      properties:
        seasonNumber:
          type: integer
        episodes:
          type: array
          items:
            $ref: '#/components/schemas/episode'
      
    episode:
      type: object
      properties:
        episodeUid:
          type: string
        episodeTitle:
          type: string
        episodeNumber:
          type: integer
          format: int64
        episodeSerialNumber:
          type: string
    
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
      example:
        code: "400"
        message : "Bad Request"
